# FMSPy - Copyright (c) 2009 Andrey Smirnov.
#
# See COPYRIGHT for details.
#
# Chat example, Flash part
# Requires haxe (http://haxe.org/)
# 

all: chat.swf

chat.swf: app.hxml Chat.hx
	haxe app.hxml
